name: allervie-dashboard
region: nyc
services:
  - name: web
    github:
      repo: jhillbht/allervie-dashboard
      branch: main
      deploy_on_push: true
    
    # Build configuration for stable installs
    build_command: |
      # Clean environment
      rm -rf node_modules

      # Copy npmrc for consistent installs
      cp .npmrc $HOME/.npmrc
      
      # Install dependencies using plain npm install
      npm install --prefer-offline

      # Build with production settings
      npm run build
    
    run_command: npm start
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    
    # Environment variables
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8080"
      
      # Supabase configuration  
      - key: VITE_SUPABASE_URL
        scope: BUILD_TIME
        type: SECRET
      - key: VITE_SUPABASE_ANON_KEY
        scope: BUILD_TIME
        type: SECRET