name: allervie-dashboard
region: nyc
services:
  - name: web
    github:
      repo: jhillbht/allervie-dashboard
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: VITE_SUPABASE_URL
        scope: BUILD_TIME
        type: SECRET
      - key: VITE_SUPABASE_ANON_KEY
        scope: BUILD_TIME
        type: SECRET
      - key: VITE_GA_MEASUREMENT_ID
        scope: BUILD_TIME
        type: SECRET
      - key: VITE_GOOGLE_ADS_CONVERSION_IDS
        scope: BUILD_TIME
        type: SECRET
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    cors:
      allow_origins:
        - "https://*.allervie.com"
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Authorization
        - Content-Type
      max_age: "86400"
    alert:
      rule: CPU_UTILIZATION
      value: 90
      operator: GREATER_THAN
      window: FIVE_MINUTES
      period: TWENTY_FOUR_HOURS