name: allervie-dashboard
region: sgp
services:
  - name: dashboard
    instance_size_slug: basic-xxs
    instance_count: 1
    github:
      repo: jhillbht/allervie-dashboard-aesthetic
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    health_check:
      http_path: /health
      port: 8080
      initial_delay_seconds: 10
      period_seconds: 5
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 3
    envs:
      # Runtime Environment
      - key: NODE_ENV
        value: production
      
      # Supabase Configuration
      - key: VITE_SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${VITE_SUPABASE_URL}
      - key: VITE_SUPABASE_ANON_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${VITE_SUPABASE_ANON_KEY}
      
      # Google OAuth Configuration
      - key: VITE_GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
        value: ${VITE_GOOGLE_CLIENT_ID}
      - key: VITE_GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: ${VITE_GOOGLE_CLIENT_SECRET}
      - key: VITE_OAUTH_REDIRECT_URI
        scope: RUN_TIME
        value: "https://seal-app-3mp4e.ondigitalocean.app/auth/callback"
      
      # Application Configuration
      - key: VITE_API_URL
        scope: RUN_TIME
        value: "https://seal-app-3mp4e.ondigitalocean.app"
      - key: VITE_ALLOWED_DOMAINS
        scope: RUN_TIME
        value: "allervie.com"