name: allervie-dashboard
region: nyc
services:
  - name: web
    github:
      repo: jhillbht/allervie-dashboard
      branch: main
      deploy_on_push: true
    
    # Build configuration with simplified dependency installation
    build_command: |
      echo "Running build with dependency installation..."
      rm -rf node_modules
      npm install
      npm run build
    
    run_command: npm start
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    
    # Environment variables
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      
      # Supabase configuration
      - key: VITE_SUPABASE_URL
        scope: BUILD_TIME
        type: SECRET
      - key: VITE_SUPABASE_ANON_KEY
        scope: BUILD_TIME
        type: SECRET