name: allervie-dashboard
region: nyc
services:
  - name: web
    github:
      repo: jhillbht/allervie-dashboard
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: |
      if [ ! -f "package-lock.json" ]; then
        echo "No package-lock.json found, running npm install..."
        npm install
      else
        echo "Using existing package-lock.json..."
        npm ci
      fi
      npm run build
    run_command: npm start
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    
    # Route configuration
    routes:
      - path: /
        preserve_path_prefix: true
    
    # Environment variables
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      
      # Supabase configuration
      - key: VITE_SUPABASE_URL
        scope: BUILD_TIME
        type: SECRET
      - key: VITE_SUPABASE_ANON_KEY
        scope: BUILD_TIME
        type: SECRET
      
      # Google Analytics configuration
      - key: VITE_GA_MEASUREMENT_ID
        scope: BUILD_TIME
        type: SECRET
      
      # Google Ads configuration
      - key: VITE_GOOGLE_ADS_CONVERSION_IDS
        scope: BUILD_TIME
        type: SECRET
    
    # Health check configuration
    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 15
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # CORS configuration
    cors:
      allow_origins:
        - "https://*.allervie.com"
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Authorization
        - Content-Type
      max_age: "86400"  # 24 hours
    
    # Alert configuration
    alert:
      rule: CPU_UTILIZATION
      value: 90
      operator: GREATER_THAN
      window: FIVE_MINUTES
      period: TWENTY_FOUR_HOURS