name: lead-generation-dashboard
services:
  - name: web
    git:
      branch: main
      repo_clone_url: ${_REPO_URL}
    build_command: npm run build
    run_command: npm run preview
    envs:
      - key: VITE_SUPABASE_URL
        value: ${VITE_SUPABASE_URL}
      - key: VITE_SUPABASE_ANON_KEY
        value: ${VITE_SUPABASE_ANON_KEY}
    http_port: 4173
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /