// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccsqfaobfzngvmhpnogi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc3FmYW9iZnpuZ3ZtaHBub2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4OTQ5NTQsImV4cCI6MjA1MjQ3MDk1NH0.ZjUrqS0oKF_RxZQilHaDHSlV5Q4DyV95poG0mQR7YcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);