name: Branch Protection Rules

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Run tests
        run: |
          npm test
          
      - name: Type check
        run: |
          npm run type-check

  protect:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Protect branch
        uses: benjefferies/branch-protection-bot@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          enforce_admins: false
          required_status_checks: true
          required_pull_request_reviews: true
          dismiss_stale_reviews: true